const items = [
    {
      id: 1,
      name: "3 Idiots",
      description: "A comedy-drama film about friendship and the education system in India.",
      category: "Movie",
      image: "https://upload.wikimedia.org/wikipedia/en/d/df/3_idiots_poster.jpg",
    },
    {
      id: 2,
      name: "Dangal",
      description: "A biographical sports drama a father training his daughters to become wrestlers.",
      category: "Movie",
      image: "https://upload.wikimedia.org/wikipedia/en/9/99/Dangal_Poster.jpg",
    },
    {
      id: 3,
      name: "Sholay",
      description: "An action-adventure film about two criminals hired to capture a ruthless bandit.",
      category: "Movie",
      image: "https://upload.wikimedia.org/wikipedia/en/5/52/Sholay-poster.jpg",
    },
    {
      id: 4,
      name: "Chennai Express",
      description: "A romantic comedy-action film about a man's journey that takes unexpected turns.",
      category: "Movie",
      image: "https://th.bing.com/th?id=OIP.5As3LaKXRcrs-pIRKrFmEAHaJ4&w=216&h=288&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    },
    {
      id: 5,
      name: "Lagaan",
      description: "A historical sports drama where villagers unite to play cricket against British officers.",
      category: "Movie",
      image: "https://upload.wikimedia.org/wikipedia/en/b/b6/Lagaan.jpg",
    },
    {
      id: 6,
      name: "Kabhi Khushi Kabhie Gham",
      description: "A family drama the relation and values with a family.",
      category: "Movie",
      image: "https://th.bing.com/th/id/OIP.m9PVEuWSY7Nok3NrmDQnjgAAAA?w=122&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    },
    {
      id: 7,
      name: "Dilwale Dulhania Le Jayenge",
      description: "A romantic film about love, tradition, and family values.",
      category: "Movie",
      image: "https://th.bing.com/th/id/OIP.TPj8BI-1rYYpgchKOEtvFAHaKe?w=208&h=295&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    },
    {
      id: 8,
      name: "Bajrangi Bhaijaan",
      description: "A drama about a kind man helping a mute girl with her family across the border.",
      category: "Movie",
      image: "https://th.bing.com/th/id/OIP._do5CVY-W-2PVMX4U3GlzgHaKv?w=130&h=187&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    },
    {
      id: 9,
      name: "Padmaavat",
      description: "A historical drama based on the story of Queen Padmavati and her courage.",
      category: "Movie",
      image: "https://th.bing.com/th/id/OIP.SdDViq9q75oDHcJLZS2HZQHaLG?w=115&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7",
    },
  ];
export default items;  