const data = [
  {
    title: "Cpp Intermediate 1",
    image: "https://gstatic.com/classroom/themes/img_read.jpg",
    description: "Intermediate level C++ course",
    batch: "Batch A",
    instructor: "John Doe",
    date: "2023-12-15",
  },
  {
    title: "CPP SESSION BATCH R",
    image: "https://gstatic.com/classroom/themes/img_learnlanguage.jpg",
    description: "C++ session for batch R",
    batch: "Batch R",
    instructor: "Jane Smith",
    date: "2023-11-20",
  },
  {
    title: "REACT NODE BATCH K",
    image: "https://gstatic.com/classroom/themes/img_bookclub.jpg",
    description: "React and Node.js batch K",
    batch: "Batch K",
    instructor: "David Lee",
    date: "2023-12-10",
  },
  {
    title: "CPP Session BATCH-Q",
    image: "https://gstatic.com/classroom/themes/Honors.jpg",
    description: "C++ session for batch Q",
    batch: "Batch Q",
    instructor: "Sarah Jones",
    date: "2023-11-25",
  },
  {
    title: "Frontend Batch-N Physical JP",
    image: "https://gstatic.com/classroom/themes/img_reachout.jpg",
    description: "Frontend development course batch N",
    batch: "Batch N",
    instructor: "Michael Brown",
    date: "2023-12-20",
  },
  {
    title: "CPP(I/J) Prajjal sir Physical JP",
    image: "https://gstatic.com/classroom/themes/img_backtoschool.jpg",
    description: "C++ course by Prajjal sir",
    batch: "Batch I/J",
    instructor: "Prajjal Sir",
    date: "2023-12-18",
  },
  {
    title: "CPP session Batch physical JP",
    image: "https://gstatic.com/classroom/themes/img_bookclub.jpg",
    description: "C++ session for January 2024",
    batch: "Batch 13",
    instructor: "John Doe",
    date: "2024-01-13",
  },
  {
    title: "CPP SESSIONS BATCH-I NOV",
    image: "https://gstatic.com/classroom/themes/img_backtoschool.jpg",
    description: "C++ sessions for batch I 2023",
    batch: "Batch I",
    instructor: "Jane Smith",
    date: "2023-11-01",
  },
  {
    title: "C-LOGICAL SESSIONS BATCH-M, DEC 2023-Physical JP",
    image: "https://gstatic.com/classroom/themes/img_breakfast.jpg",
    description: "C Logical Sessions for batch M",
    batch: "Batch M",
    instructor: "David Lee",
    date: "2023-12-01",
  },
  {
    title: "LINUX/ GIT SESSIONS 4/12/23-Physical JP-DEC 25",
    image: "https://gstatic.com/classroom/themes/Honors.jpg",
    description: "Linux and Git sessions",
    batch: "Batch 4/12/23",
    instructor: "Sarah Jones",
    date: "2023-12-25",
  },
];
export default data;